
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Articles: /categories/articles
  Notes: /categories/notes
  Work: /categories/work

# feed
atom: /atom.xml

# Miscelaneous
favicon: /favicon.png

# loaded in the head
stylesheets:
- /css/main.css
