# Header
menu:
  Home: /
  About: /about
  Articles: /categories/articles
  Notes: /categories/notes
  Work: /categories/work
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar:
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscelaneous
favicon: /favicon.png
twitter: ThatIanRose
