# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar:
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscelaneous
favicon: /favicon.png
twitter: ThatIanRose
google_plus:
fb_admins:
fb_app_id:
